#!/bin/bash
# Autonomous Data Manager - HOURLY EXECUTION
# Schedule: 0 * * * *
# Generated by AGI Optimization Query System

# Set environment
export PYTHONPATH=/home/ubuntu/wealthyrobot:$PYTHONPATH

# Log start
echo "$(date): Autonomous Data Manager starting..." >> /home/ubuntu/wealthyrobot/autonomous_manager.log

# Execute optimization with timeout (5 minutes max)
timeout 300s python3 /home/ubuntu/wealthyrobot/agi_disk_optimizer.py >> /home/ubuntu/wealthyrobot/autonomous_manager.log 2>&1

# Check exit status
if [ $? -eq 124 ]; then
    echo "$(date): Autonomous Data Manager timed out" >> /home/ubuntu/wealthyrobot/autonomous_manager.log
elif [ $? -eq 0 ]; then
    echo "$(date): Autonomous Data Manager completed successfully" >> /home/ubuntu/wealthyrobot/autonomous_manager.log
else
    echo "$(date): Autonomous Data Manager failed with exit code $?" >> /home/ubuntu/wealthyrobot/autonomous_manager.log
fi

# Log completion
echo "$(date): Autonomous Data Manager finished" >> /home/ubuntu/wealthyrobot/autonomous_manager.log
echo "---" >> /home/ubuntu/wealthyrobot/autonomous_manager.log
