assets:
  - symbol: USDC
    asset_id: 31566704
    enabled: true
    seed_trade_micro: 10000
  - symbol: USDT
    asset_id: 312769
    enabled: true
    seed_trade_micro: 10000
  - symbol: goBTC
    asset_id: 386192725
    enabled: true
    seed_trade_micro: 10000
  - symbol: goETH
    asset_id: 386195940
    enabled: true
    seed_trade_micro: 10000
  - symbol: OPUL
    asset_id: 287867876
    enabled: true
    seed_trade_micro: 10000
  - symbol: GARD
    asset_id: 684649988
    enabled: true
    seed_trade_micro: 10000
  - symbol: CHIPS
    asset_id: 388592191
    enabled: true
    seed_trade_micro: 10000
