# Development Environment Configuration
environment: development
log_level: DEBUG
testing_mode: false  # Real DeFi transactions for production

# Trading Parameters
trading:
  max_position_size: 0.1  # Maximum ALGO per trade
  min_position_size: 0.001  # Minimum ALGO per trade
  max_daily_trades: 10
  risk_tolerance: medium
  
# Protocol Settings
protocols:
  tinyman:
    enabled: true
    max_slippage: 0.5  # 0.5%
    gas_limit: 1000000
    
  pact:
    enabled: true
    max_slippage: 0.3  # 0.3%
    gas_limit: 800000
    
  folks:
    enabled: true
    max_slippage: 0.2  # 0.2%
    gas_limit: 600000
    


# Risk Management
risk_management:
  max_portfolio_risk: 0.3  # 30% max portfolio risk
  stop_loss_percentage: 0.15  # 15% stop loss
  take_profit_percentage: 0.25  # 25% take profit
  
# Monitoring
monitoring:
  opportunity_scan_interval: 60
  health_check_interval: 300
  performance_metrics_interval: 3600  # 1 hour
  
# API Rate Limiting
rate_limits:
  algod_requests_per_minute: 100
  indexer_requests_per_minute: 50
  defi_requests_per_minute: 200
