aggressiveness: balanced
base_trade_micro: 1000
enable_arbitrage: true
enable_momentum: true
enable_yield: true
enable_flash: true
arbitrage_threshold_bps: 100
momentum_threshold_bps: 100
consult_interval_sec: 3600

