# WealthyRobot Autonomous Trading Fund Configuration
fund_name: "WealthyRobot Autonomous Trading Fund"
version: "2.0.0"
autonomous_mode: true
auto_upgrade: true
strategy_discovery: true

# Risk Management Configuration
risk_management:
  max_portfolio_risk: 0.3          # 30% maximum portfolio risk
  max_daily_loss: 0.1              # 10% maximum daily loss
  position_sizing: "kelly_criterion" # Position sizing strategy
  stop_loss_percentage: 0.15       # 15% stop loss
  take_profit_percentage: 0.25     # 25% take profit
  
# Agent Configuration
agents:
  ceo_agent: true                  # Ultimate CEO Agent
  claude_agent: true               # Claude AI Agent
  trading_agent: true              # Trading Execution Agent
  risk_agent: true                 # Risk Management Agent
  strategy_agent: true             # Strategy Discovery Agent
  
# Upgrade Schedule
upgrade_schedule:
  check_interval_hours: 6          # Check for upgrades every 6 hours
  auto_upgrade: true               # Automatically upgrade when available
  backup_before_upgrade: true      # Create backup before upgrading
  
# Strategy Discovery
strategy_discovery:
  scan_interval_hours: 12          # Scan for new strategies every 12 hours
  auto_integrate: true             # Automatically integrate new strategies
  backtest_new_strategies: true    # Backtest new strategies before integration
  
# Trading Parameters
trading:
  max_position_size: 0.1           # Maximum ALGO per trade
  min_position_size: 0.001         # Minimum ALGO per trade
  max_daily_trades: 10             # Maximum trades per day
  opportunity_score_threshold: 50  # Minimum score for autonomous trading
  
# Portfolio Management
portfolio:
  rebalance_interval_hours: 24     # Portfolio rebalancing frequency
  optimization_enabled: true       # Enable portfolio optimization
  performance_tracking: true       # Track performance metrics
  
# Monitoring and Reporting
monitoring:
  health_check_interval_minutes: 60 # System health check frequency
  report_generation: "daily"       # Report generation frequency
  log_retention_days: 30           # Log retention period
  
# Integration Settings
integration:
  claude_agent_enabled: true       # Enable Claude agent integration
  ceo_agent_enabled: true          # Enable CEO agent integration
  external_data_sources: true      # Enable external data sources
  api_rate_limiting: true          # Enable API rate limiting
  
# Security Settings
security:
  require_confirmation: false      # Require manual confirmation for trades
  max_single_trade_value: 0.1     # Maximum single trade value
  daily_loss_limit: 0.5            # Daily loss limit
  emergency_stop_enabled: true     # Enable emergency stop functionality
