# Production Environment Configuration
environment: production
log_level: INFO
testing_mode: false  # Real DeFi trades in production

# Trading Parameters
trading:
  max_position_size: 0.05  # Conservative position sizing
  min_position_size: 0.01
  max_daily_trades: 5
  risk_tolerance: low
  
# Protocol Settings
protocols:
  tinyman:
    enabled: true
    max_slippage: 0.2  # Conservative slippage
    gas_limit: 800000
    
  pact:
    enabled: true
    max_slippage: 0.15
    gas_limit: 600000
    
  folks:
    enabled: true
    max_slippage: 0.1
    gas_limit: 500000
    


# Risk Management
risk_management:
  max_portfolio_risk: 0.15  # Conservative risk
  stop_loss_percentage: 0.1  # Tight stop loss
  take_profit_percentage: 0.2
  
# Monitoring
monitoring:
  health_check_interval: 60  # More frequent checks
  opportunity_scan_interval: 300  # Less frequent scans
  performance_metrics_interval: 1800  # 30 minutes
  
# API Rate Limiting
rate_limits:
  algod_requests_per_minute: 50
  indexer_requests_per_minute: 25
  defi_requests_per_minute: 100
  
# Security
security:
  require_confirmation: true
  max_single_trade_value: 0.1  # Max 0.1 ALGO per trade
  daily_loss_limit: 0.5  # Max 0.5 ALGO daily loss
