# Real Trading Configuration - Hybrid Algorand Trading Empire
# Controls actual blockchain transaction execution

real_trading:
  enabled: true
  mode: "production"  # production, testing, simulation
  
# Wallet Configuration
wallet:
  auto_load_from_env: true
  env_file: ".env"
  required_credentials:
    - "ALGORAND_WALLET_ADDRESS"
    - "ALGORAND_WALLET_MNEMONIC"
  
# Risk Management for Real Trading
risk_management:
  max_trade_amount_algo: 0.1  # Maximum 0.1 ALGO per trade
  max_daily_trades: 5  # Maximum 5 trades per day
  max_daily_volume_algo: 0.5  # Maximum 0.5 ALGO total volume per day
  min_reliability_score: 90  # Only trade opportunities with 90%+ reliability
  
# Trade Execution Settings
trade_execution:
  auto_execute: true  # Automatically execute trades when conditions met
  confirmation_required: false  # Require manual confirmation (set to true for safety)
  execution_delay_seconds: 10  # Delay before executing trades
  
  # Trade Types
  yield_farming:
    enabled: true
    max_amount_algo: 0.1
    protocols: ["pact_finance"]
    
  dex_trading:
    enabled: true
    max_amount_algo: 0.05
    protocols: ["tinyman_v2"]
    
  lending:
    enabled: true
    max_amount_algo: 0.1
    protocols: ["folks_finance"]
    
  arbitrage:
    enabled: false  # Disabled for safety
    max_amount_algo: 0.02
    
# Protocol Integration
protocols:
  tinyman_v2:
    enabled: true
    app_id: 1002541853
    max_slippage: 0.02  # 2%
    
  pact_finance:
    enabled: true
    app_id: 148607001
    max_slippage: 0.03  # 3%
    
  folks_finance:
    enabled: true
    app_id: 148607002
    max_slippage: 0.01  # 1%
    
# Transaction Settings
transactions:
  gas_limit: 1000
  max_fee: 0.001  # Maximum 0.001 ALGO fee
  retry_attempts: 3
  retry_delay_seconds: 30
  
# Monitoring and Alerts
monitoring:
  trade_execution_logging: true
  blockchain_confirmation_tracking: true
  balance_monitoring: true
  profit_loss_tracking: true
  
  alerts:
    trade_executed: true
    trade_failed: true
    balance_low: true
    daily_limit_reached: true
    
# Safety Features
safety:
  emergency_stop_enabled: true
  emergency_stop_threshold: 0.8  # Stop at 80% of daily limit
  dry_run_mode: false  # Set to true to simulate trades without execution
  
# Blockchain Configuration
blockchain:
  network: "mainnet"  # mainnet, testnet, betanet
  algod_address: "https://mainnet-api.algonode.cloud"
  algod_token: ""
  indexer_address: "https://mainnet-idx.algonode.cloud"
  indexer_token: ""
  
# Real Transaction Settings
real_transactions:
  enabled: true
  confirm_transactions: true
  wait_for_confirmation: true
  confirmation_timeout: 60  # seconds
  
# Testing and Development
development:
  test_mode: false
  mock_transactions: false
  simulated_balances: false
