# System Optimization Configuration for Current Hardware
# Maximizes AGI performance without overloading the system

system_limits:
  # CPU and Memory Constraints
  max_cpu_percent: 75
  max_memory_percent: 80
  max_disk_percent: 85

  # Process Limits
  max_concurrent_processes: 8
  max_threads_per_process: 4

  # Performance Targets
  target_response_time: 5.0  # seconds
  target_cycle_time: 300    # 5 minutes between major cycles

agi_cycle_optimization:
  # Timing Configuration
  cycle_interval_seconds: 300  # 5 minutes between full cycles
  quick_cycle_interval: 60     # 1 minute for quick status checks
  emergency_cycle_interval: 30 # 30 seconds during high activity

  # Resource Allocation
  memory_budget_mb: 512
  cpu_budget_percent: 50

  # Feature Priorities (1-10 scale)
  priorities:
    brain_research: 8
    business_optimization: 7
    self_improvement: 6
    system_monitoring: 9
    logging: 4

  # Batch Processing
  batch_size:
    insight_processing: 5
    data_collection: 10
    optimization_cycles: 3

performance_monitoring:
  # Monitoring Intervals
  system_check_interval: 30
  performance_log_interval: 60
  resource_alert_threshold: 85

  # Auto-optimization
  enable_auto_optimization: true
  optimization_interval: 600  # 10 minutes

resource_management:
  # Memory Management
  enable_memory_optimization: true
  memory_cleanup_interval: 300
  max_cache_size_mb: 256

  # Storage Management
  enable_log_rotation: true
  max_log_files: 10
  max_log_age_days: 7

  # CPU Management
  enable_cpu_throttling: true
  high_load_threshold: 70
  throttle_backoff_seconds: 30

optimization_strategies:
  # When system is under load
  high_load_actions:
    - reduce_cycle_frequency
    - disable_non_essential_features
    - increase_batch_sizes
    - reduce_parallel_processing

  # When system has spare capacity
  low_load_actions:
    - increase_cycle_frequency
    - enable_additional_features
    - reduce_batch_sizes
    - enable_parallel_processing

feature_gates:
  # Enable/disable features based on system capacity
  brain_research: true
  business_optimization: true
  self_improvement: true
  advanced_logging: false  # Disabled to save resources
  detailed_monitoring: true
  web_research: false      # Disabled - needs more resources
  predictive_analytics: false  # Disabled - needs more resources

emergency_protocols:
  # System overload protection
  enable_emergency_mode: true
  emergency_threshold_cpu: 90
  emergency_threshold_memory: 90

  emergency_actions:
    - pause_non_essential_processes
    - reduce_cycle_frequency
    - clear_caches
    - enable_minimal_mode
