# Test Environment Configuration
environment: test
log_level: INFO
testing_mode: true  # Safe testing mode - no real trades

# Trading Parameters
trading:
  max_position_size: 100  # Test amounts
  min_position_size: 10
  max_daily_trades: 10
  risk_tolerance: high  # Allow more test trades
  
# Protocol Settings
protocols:
  tinyman:
    enabled: true
    max_slippage: 0.5  # Higher slippage for testing
    gas_limit: 1000000
    
  pact:
    enabled: true
    max_slippage: 0.5
    gas_limit: 800000
    
  folks:
    enabled: true
    max_slippage: 0.5
    gas_limit: 600000

# Risk Management
risk_management:
  max_portfolio_risk: 0.5  # Higher risk for testing
  stop_loss_percentage: 0.2
  take_profit_percentage: 0.3
  
# Monitoring
monitoring:
  health_check_interval: 30  # More frequent checks for testing
  opportunity_scan_interval: 60  # More frequent scans for testing
  performance_metrics_interval: 300  # 5 minutes
  
# API Rate Limiting
rate_limits:
  algod_requests_per_minute: 100
  indexer_requests_per_minute: 50
  defi_requests_per_minute: 200
  
# Security
security:
  require_confirmation: false  # No confirmation needed for tests
  max_single_trade_value: 1000  # Higher test amounts
  daily_loss_limit: 1000  # Higher test limits
